version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        environment:
            APP_ENV: production
            APP_KEY: base64:8Ml6QyzLkUjUjl8ESipYu5CQ+yc1ddqwfccuaU1MDlI=
            APP_DEBUG: false
            APP_URL: https://seuapp.onrender.com
            DB_CONNECTION: pgsql
            DB_HOST: dpg-d3ikcsjipnbc73e90vn0-a
            DB_PORT: 5432
            DB_DATABASE: pokedex_db_pbgj
            DB_USERNAME: pokedex_db_pbgj_user
            DB_PASSWORD: zaYKhBw7jzPC8ZSSTV6dSf0aOwGG6NR0
        depends_on:
            - db

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: pokedex
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
