version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        environment:
            APP_ENV: production
            APP_KEY: base64:SEU_APP_KEY_AQUI
            APP_DEBUG: false
            APP_URL: https://seuapp.onrender.com
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: pokedex
            DB_USERNAME: root
            DB_PASSWORD: root
        depends_on:
            - db

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: pokedex
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
